# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secretsanta.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SecretSantaWindow(object):
    def setupUi(self, SecretSantaWindow):
        SecretSantaWindow.setObjectName("SecretSantaWindow")
        SecretSantaWindow.resize(800, 600)
        SecretSantaWindow.setStyleSheet("background:aliceblue;")
        self.centralwidget = QtWidgets.QWidget(SecretSantaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 521))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(1, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setStyleSheet("background-color:ghostwhite;")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(520, 140, 261, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("background-color:steelblue;\n"
"border-radius:10px;")
        self.addButton.setObjectName("addButton")
        self.verticalLayout_2.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.removeButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeButton.sizePolicy().hasHeightForWidth())
        self.removeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeButton.setFont(font)
        self.removeButton.setStyleSheet("background-color:steelblue;\n"
"border-radius:10px;")
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout_2.addWidget(self.removeButton)
        self.editButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editButton.setFont(font)
        self.editButton.setStyleSheet("background-color:steelblue;\n"
"border-radius:10px;")
        self.editButton.setObjectName("editButton")
        self.verticalLayout_2.addWidget(self.editButton)
        self.sendButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendButton.setFont(font)
        self.sendButton.setStyleSheet("background-color:limegreen;\n"
"border-radius:10px;")
        self.sendButton.setObjectName("sendButton")
        self.verticalLayout_2.addWidget(self.sendButton)
        SecretSantaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecretSantaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        SecretSantaWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecretSantaWindow)
        self.statusbar.setObjectName("statusbar")
        SecretSantaWindow.setStatusBar(self.statusbar)
        self.loadFromCSV_Button = QtWidgets.QAction(SecretSantaWindow)
        self.loadFromCSV_Button.setObjectName("loadFromCSV_Button")
        self.saveToCSV_Button = QtWidgets.QAction(SecretSantaWindow)
        self.saveToCSV_Button.setObjectName("saveToCSV_Button")
        self.menuOptions.addAction(self.loadFromCSV_Button)
        self.menuOptions.addAction(self.saveToCSV_Button)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(SecretSantaWindow)
        QtCore.QMetaObject.connectSlotsByName(SecretSantaWindow)

    def retranslateUi(self, SecretSantaWindow):
        _translate = QtCore.QCoreApplication.translate
        SecretSantaWindow.setWindowTitle(_translate("SecretSantaWindow", "MainWindow"))
        self.addButton.setText(_translate("SecretSantaWindow", "Add"))
        self.removeButton.setText(_translate("SecretSantaWindow", "Remove"))
        self.editButton.setText(_translate("SecretSantaWindow", "Edit"))
        self.sendButton.setText(_translate("SecretSantaWindow", "Send"))
        self.menuOptions.setTitle(_translate("SecretSantaWindow", "Options"))
        self.loadFromCSV_Button.setText(_translate("SecretSantaWindow", "Load From CSV File"))
        self.saveToCSV_Button.setText(_translate("SecretSantaWindow", "Save to CSV File"))

